FROM node:16.15.0-alpine3.15 as build-stage

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/

RUN npm install

COPY ./ /app/

EXPOSE 80

RUN npm run build

FROM nginx:1.22.0-alpine
COPY --from=build-stage /app/build/ /usr/share/nginx/html
